export enum ModalAction {
  OPEN_MODAL = "OPEN_MODAL",
  CLOSE_MODAL = "CLOSE_MODAL",
  CLOSE_COMMON_MODAL = "CLOSE_COMMON_MODAL",
}

export enum ModalType {
  ERROR_MODAL = "ERROR_MODAL",
  NOTE_MODAL = "NOTE_MODAL",
  DELETE_MODAL = "DELETE_MODAL",
  NAME_MODAL = "NAME_MODAL",
  PREVIEW_MODAL = "PREVIEW_MODAL",
}

